{
 "title": "New dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "logs per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(logs_ingested_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "total alerts created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "alerts_created_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Latency  p95",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{p95}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le, job) (rate(http_request_duration_seconds_bucket[5m])))",
     "legendFormat": "{{p50}}"
    }
   ]
  },
  {
   "title": "service health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"log-collector\"}",
     "legendFormat": "log collector"
    },
    {
     "expr": "up{job=\"alert-manager\"}",
     "legendFormat": "alert manager"
    },
    {
     "expr": "\nup{job=\"threat-intel\"}",
     "legendFormat": "threat intel"
    }
   ]
  }
 ]
}