auth_enabled: false
server:
  http_listen_port: 3100
ingester:
  lifecycler:
    ring:
      replication_factor: 1
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/chunks
  filesystem:
    directory: /loki/chunks
schame_config:
  configs: 
    - from: 2004-01-01
      store: boltdb_shipper
      object_store: filesystem
      schema: v11
      index: 
        prefix: index_
        period: 24h 
